### ISSUE TITLE
Non Presence TDC -- error not generated

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#201]
Using IZ-AD-1.1_Send_V04_Z22:
Take PID-29.1 TDC=non presence, Usage= C(RE/X) if PID-30 is valued “Y”
PID-30 TDC=Test casefixed = N

If PID-30 is valued “Y” the tool should generate the PID-30 test case fixed error and a PID-29.1 non presence error. (I think this is the expected behavior)

The tool generated only the test case fixed  error on PID-30:
TCA-487 - Expected test case fixed content is missing. The value 'Y' at 'Field PID-30 (Patient Death Indicator)' does not match the expected value “N”

**Comment by Jungyubw** [comment]
fixed. it will shown at next deployment.

**Comment by smartinez290** [comment]
The tool was deployed,  12/03/2015 02:57:17 -- I am  still getting only one error.

**Comment by smartinez290** [comment]
The error is generated but the path is incorrect. 
![nopresence](https://cloud.githubusercontent.com/assets/14842422/11594956/e2f15110-9a7a-11e5-8f11-13989bc97d29.png)

**Comment by smartinez290** [comment]
I am going to close this one and create a new ticket.
